app:
  id: com.example.app
  name: Example App
  version: 1.0
  build_number: 1

dynamic_config:
  enabled: false
  access_token: access_token

permissions:
  - internet

integrations:
  onesignal:
    enabled: true
    app_id: app_id
  admob:
    enabled: true
    app_id: app_id
    banner_id: banner_id
    interstitial_id: interstitial_id