# Version catalog updates generated at 2024-07-27T09:18:06.8536759
#
# Contents of this file will be applied to libs.versions.toml when running versionCatalogApplyUpdates.
#
# Comments will not be applied to the version catalog when updating.
# To prevent a version upgrade, comment out the entry or remove it.
#
[libraries]
# From version 1.9.1 --> 1.10.0-alpha01
activity-compose = "androidx.activity:activity-compose:1.10.0-alpha01"
# From version 1.13.1 --> 1.15.0-alpha01
core-ktx = "androidx.core:core-ktx:1.15.0-alpha01"
# From version 1.0.1 --> 1.2.0-alpha01
core-splashscreen = "androidx.core:core-splashscreen:1.2.0-alpha01"
# From version 1.0.1 --> 1.1.0-alpha01
documentfile = "androidx.documentfile:documentfile:1.1.0-alpha01"
# From version 2.48.1 --> 2.51.1
hilt-agp = "com.google.dagger:hilt-android-gradle-plugin:2.51.1"
# From version 2.49 --> 2.51.1
hilt-android = "com.google.dagger:hilt-android:2.51.1"
# From version 2.49 --> 2.51.1
hilt-android-testing = "com.google.dagger:hilt-android-testing:2.51.1"
# From version 2.49 --> 2.51.1
hilt-compiler = "com.google.dagger:hilt-compiler:2.51.1"
# From version 2.7.7 --> 2.8.0-beta06
navigation-compose = "androidx.navigation:navigation-compose:2.8.0-beta06"
# From version 2.7.7 --> 2.8.0-beta06
navigation-testing = "androidx.navigation:navigation-testing:2.8.0-beta06"

[plugins]
# From version 8.5.1 --> 8.7.0-alpha03
android-application = "com.android.application:8.7.0-alpha03"
# From version 2.0.0 --> 2.0.20-Beta2
compose-compiler = "org.jetbrains.kotlin.plugin.compose:2.0.20-Beta2"
# From version 2.44 --> 2.51.1
dagger-hilt-android = "com.google.dagger.hilt.android:2.51.1"
# From version 2.0.0-1.0.23 --> 2.0.20-Beta2-1.0.23
devtools-ksp = "com.google.devtools.ksp:2.0.20-Beta2-1.0.23"
# From version 2.0.0 --> 2.0.20-Beta2
jetbrains-kotlin-android = "org.jetbrains.kotlin.android:2.0.20-Beta2"
