object Versions {
    const val core = "1.9.0"
    const val lifecycleRunTime = "2.6.1"
    const val activityCompose = "1.7.2"
    const val navigation = "2.7.1"
    const val googleFonts = "1.4.3"
    const val coilCompose = "2.4.0"
    const val daggerHilt = "2.44"
    const val hiltNavigationCompose = "1.0.0"
    const val retrofit = "2.9.0"
    const val gson = "2.9.1"
    const val oneSignal = "[4.0.0, 4.99.99]"
    const val splashScreen = "1.0.0"
    const val junit = "4.13.2"
    const val extJunit = "1.1.5"
    const val espressoCore = "3.5.1"
}