name: Dependency Update

on:
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  update:
    name: Update Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: gradle

      - name: Update Dependencies
        run: ./gradlew versionCatalogUpdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_PAT }}
          commit-message: 🤖 Update Dependencies
          committer: nosyntax-bot <github-bot@nosyntax.io>
          author: nosyntax-bot <github-bot@nosyntax.io>
          branch: update-dependencies
          delete-branch: true
          title: 🤖 Update Dependencies
          body: |
            📦 Dependencies updated!

            Hey team, I’ve updated our app dependencies. Please verify everything before merging.

            Cheers! ☕