name: Dependency Update

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  update:
    name: Update Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: gradle

      - name: Copy CI App Config
        run: cp .github/ci-app-config.yml app-config.yml

      - name: Update Dependencies
        run: ./gradlew versionCatalogUpdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.BOT_PAT }}
          commit-message: 🤖 Update Dependencies
          committer: nosyntax-bot <github-bot@nosyntax.io>
          author: nosyntax-bot <github-bot@nosyntax.io>
          branch: bot-update-dependencies
          delete-branch: true
          title: 🤖 Update Dependencies
          body: |
            🚀 Dependencies Updated!

            I’ve handled the dependency updates for you. Give everything a quick check and make sure it’s all good before merging.

            Happy coding! 🤖🎉