name: Signing Setup

on:
  workflow_dispatch:
    inputs:
      project-id:
        description: 'Project ID'
        required: true

jobs:
  signing-setup:
    name: Signing Setup
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ inputs.project-id }}

    steps:
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Keystore
        run: |
          # Generate store and key passwords
          PASSWORD=$(openssl rand -base64 16 | tr -d '\n')

          # Generate keystore
          keytool -genkey -v \
            -keystore signing.keystore \
            -alias $PROJECT_ID \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass $PASSWORD \
            -keypass $PASSWORD \
            -dname "O=$PROJECT_ID"

          # Encode keystore file to base64 format
          base64Keystore=$(base64 -w 0 signing.keystore)
          
          # Export keystore details as environment variables
          echo "KEYSTORE_FILE=$base64Keystore" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          echo "KEY_ALIAS=$PROJECT_ID" >> $GITHUB_ENV
          echo "KEY_PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: Extract Certificate Fingerprints
        run: |
          # Retrieve keystore information to extract fingerprints
          keystoreOutput=$(keytool -list -v -keystore signing.keystore -alias $KEY_ALIAS -storepass $KEYSTORE_PASSWORD)

          # Extract SHA1 and SHA256 fingerprints
          sha1Fingerprint=$(echo "$keystoreOutput" | awk '/SHA1:/ {print $2}')
          sha256Fingerprint=$(echo "$keystoreOutput" | awk '/SHA256:/ {print $2}')
          
          # Export fingerprints as environment variables
          echo "SHA1_FINGERPRINT=$sha1Fingerprint" >> $GITHUB_ENV
          echo "SHA256_FINGERPRINT=$sha256Fingerprint" >> $GITHUB_ENV

      - name: Update Signing Settings
        run: |
          curl -s -f -X POST "https://api.nosyntax.io/actions/update_signing_settings" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -H "API-KEY: ${{ secrets.API_KEY }}" \
            -d "project_id=${{ env.PROJECT_ID }}" \
            -d "keystore_file=${{ env.KEYSTORE_FILE }}" \
            -d "keystore_password=${{ env.KEYSTORE_PASSWORD }}" \
            -d "key_alias=${{ env.KEY_ALIAS }}" \
            -d "key_password=${{ env.KEY_PASSWORD }}" \
            -d "sha1_fingerprint=${{ env.SHA1_FINGERPRINT }}" \
            -d "sha256_fingerprint=${{ env.SHA256_FINGERPRINT }}"