name: Source Code Lifecycle

on:
  workflow_dispatch:
    inputs:
      build-details:
        description: "Build Details"
        required: true
      project-details:
        description: "Project Details"
        required: true
      app-config:
        description: "App Config"
        required: true

jobs:
  configure:
    name: Configure Source Code
    runs-on: ubuntu-latest

    env:
      BUILD_ID: ${{ fromJson(inputs['build-details'])['build_id'] }}
      BUILD_ENVIRONMENT: ${{ fromJson(inputs['build-details'])['build_environment'] }}
      BUILD_OUTPUT: ${{ fromJson(inputs['build-details'])['build_output'] }}

      APP_CONFIG: ${{ inputs['app-config'] }}

      PROJECT_ID: ${{ fromJson(inputs['project-details'])['project_id'] }}
      PROJECT_ACCESS_TOKEN: ${{ fromJson(inputs['project-details'])['project_access_token'] }}
      ADS_ENABLED: ${{ fromJson(inputs['project-details'])['ads_enabled'] }}

      KEYSTORE_FILE: ${{ fromJson(inputs['project-details'])['keystore_file'] }}
      KEYSTORE_PASSWORD: ${{ fromJson(inputs['project-details'])['keystore_password'] }}
      KEY_ALIAS: ${{ fromJson(inputs['project-details'])['key_alias'] }}
      KEY_PASSWORD: ${{ fromJson(inputs['project-details'])['key_password'] }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r .github/requirements.txt

      - name: Set App Configuration
        run: |
          python .github/scripts/render_template.py \
            --template-file "app-config.yml.template" \
            --output-file "app-config.yml" \
            --data '${{ env.APP_CONFIG }}'

      - name: Generate Launcher Icons
        run: |
          python .github/scripts/generate_launcher_icons.py \
            --res-directory app/src/main/res \
            --icon-url "https://appstatic.nosyntax.io/icons/launcher/${{ env.PROJECT_ID }}.png" \
            --fallback-url "https://appstatic.nosyntax.io/icons/launcher/fallback_icon.png" \
            --auth-username "${{ secrets.APPSTATIC_AUTH_USERNAME }}" \
            --auth-password "${{ secrets.APPSTATIC_AUTH_PASSWORD }}"

      - name: Obtain Signing Key
        run: |
          echo "${{ env.KEYSTORE_FILE }}" | base64 -d > "signing.keystore"

      - name: Set Signing Properties
        run: |
          python .github/scripts/render_properties_template.py \
            --template-file "signing.properties.template" \
            --output-file "signing.properties" \
            --context \
              "KEYSTORE_FILE=signing.keystore" \
              "KEYSTORE_PASSWORD=${{ env.KEYSTORE_PASSWORD }}" \
              "KEY_ALIAS=${{ env.KEY_ALIAS }}" \
              "KEY_PASSWORD=${{ env.KEY_PASSWORD }}"

      - name: Archive Source Code
        uses: actions/upload-artifact@v4
        if: ${{ contains(env.BUILD_OUTPUT, 'source') }}
        with:
          name: sourcecode
          path: |
            .

  build:
    name: Build Release Artifact
    needs: configure
    runs-on: ubuntu-latest
    if: ${{ contains(fromJson(inputs['build-details'])['build_output'], 'apk') }}

    steps:
      - name: Download Source Code
        uses: actions/download-artifact@v4
        with:
          name: sourcecode
          path: ./

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Build Release
        run: |
          chmod +x gradlew
          if [ "${{ fromJson(inputs['project-details'])['ads_enabled'] }}" == "enabled" ]; then
            ./gradlew assembleMonetizeRelease
          else
            ./gradlew assembleRegularRelease
          fi